import turtle
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(50)
turtle.forward(100)
turtle.left(90)


turtle.up()
turtle.shape('turtle')
turtle.goto(80,0)
turtle.color('red')
turtle.color('green','blue')
turtle.down()
turtle.begin_fill()
turtle.forward(300)
turtle.right(144)
turtle.forward(300)
turtle.right(144)
turtle.forward(300)
turtle.right(144)
turtle.forward(300)
turtle.right(144)
turtle.forward(300)
turtle.right(144)
turtle.end_fill()
turtle.hideturtle()
turtle.done()